image: docker:stable

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  TRIVY_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

Kanikoize:
  tags:
    - ord1-tenant
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - |
        mkdir -p /kaniko/.docker
        echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        if [[ -z "$CI_COMMIT_TAG" ]]; then
          /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile \
            --destination $CONTAINER_TEST_IMAGE --destination $CONTAINER_RELEASE_IMAGE \
            --destination $TRIVY_IMAGE
        else
          /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile \
            --destination $CONTAINER_TEST_IMAGE --destination $CONTAINER_RELEASE_IMAGE \
            --destination $TRIVY_IMAGE --destination "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
        fi
  only:
    variables:
      - ($CI_COMMIT_BRANCH == "master") || ($CI_COMMIT_TAG != "")
  needs: []
